apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app-k8
  name: java-app-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app-k8
  template:
    metadata:
      labels:
        app: java-app-k8
    spec:
      containers:
      - image: kireeti1234/java-session
        name: kireeti1234
